### PR TITLE
[#77] Add type number for inputNumber

### PR DESCRIPTION
**Pull request by navins94**
- #77

### CODE REVIEW

**Comment by wayangalihpratama** [comment]
Hi @navins94 , 
I try to input a letter to input number, but there's no feedback from the input.

**Comment by navins94** [comment]
> Hi @navins94 , I try to input a letter to input number, but there's no feedback from the input.

@wayangalihpratama For input number in antd documentation they have suggested to add type number coz if we try to enter letters in number field it does not take that value in dom

**Comment by navins94** [comment]
> Hi @navins94, could you please also incorporate [the comment](https://github.com/akvo/akvo-react-form/issues/77#issuecomment-1427475467) to this PR

I have added that to input number and text. But we need to finalise the icons

**Comment by wayangalihpratama** [comment]
Hi @navins94 , 
Do we only add the icon for input number and text or for all question type?

**Review by wayangalihpratama — APPROVED** [review]
Hi @navins94 , 
I have made some updated to set `fieldIcons` param and move svg icon into a component.

**Pull request merged**
